various updates to mardown viewer
Deleted: README.d/md.css.jq
Modified: README.md
Added: apps/mrkdnv/1.x-master.zip
* Modified: apps/mrkdnv/@group
Added: apps/mrkdnv/markdown.zip
* Modified: apps/mrkdnv/mrkdnv
Added: apps/mrkdnv/themes/hypersoft
Added: apps/mrkdnv/themes/hypersoft.css

diff --git a/apps/mrkdnv/@group b/apps/mrkdnv/@group
--- a/apps/mrkdnv/@group
+++ b/apps/mrkdnv/@group
@@ -37,12 +37,15 @@ echo ""
 
 shared_dir=/usr/share/mrkdnv;
 
-mkdir -p $shared_dir;
+mkdir -p $shared_dir{,/themes};
 
 status=`install -vt "$installDir" "$byApplication" 2>&1 || \
 echo -n "$this: $group: installation failed to copy: " >&2;`;
 
 status=`install -vt "$shared_dir" "apps/mrkdnv/Markdown/Markdown.pl" 2>&1 || \
+echo -n "$this: $group: installation failed to copy: " >&2;`;
+
+status=`install -vt "$shared_dir/themes" apps/mrkdnv/themes/* 2>&1 || \
 echo -n "$this: $group: installation failed to copy: " >&2;`;
 
 echo "$status";
diff --git a/apps/mrkdnv/mrkdnv b/apps/mrkdnv/mrkdnv
--- a/apps/mrkdnv/mrkdnv
+++ b/apps/mrkdnv/mrkdnv
@@ -1,5 +1,32 @@
 #!/bin/bash
 
+function_js_load_css='
+function loadCSS(filename){
+  var fileref=document.createElement("link");
+  fileref.setAttribute("rel", "stylesheet");
+  fileref.setAttribute("type", "text/css");
+  fileref.setAttribute("href", filename);
+  document.getElementsByTagName("head")[0].appendChild(fileref);
+  return fileref;
+};
+'
+
+declare MRKDNV_PROFILE MRKDNV_STYLE;
+
+while [[ ${1:0:1} == - ]]; do
+	[[ $1 == -- ]] && { shift; break; }
+	[[ $1 =~ ^--profile$|^-p$ ]] && {
+		MRKDNV_PROFILE=-o\ Seed.include\("'$2'"\)\;;
+		shift 2; continue;
+	}
+	[[ $1 =~ ^--style$|^-s$ ]] && {
+		MRKDNV_STYLE="-o loadCSS('$2');";
+		shift 2; continue;
+	}
+	echo "$0: error: incorrect parameter \`$1'" >&2;
+	exit 9;
+done
+
 lib=/usr/share/mrkdnv/Markdown.pl;
 
 [[ -e $lib ]] || {
@@ -12,6 +39,10 @@ lib=/usr/share/mrkdnv/Markdown.pl;
 	debug=-D;
 }
 
+[[ -z "$MRKDNV_STYLE" && -z "$MRKDNV_PROFILE" ]] && {
+	MRKDNV_PROFILE='-o Seed.include("/usr/share/mrkdnv/themes/hypersoft")';
+}
+
 # Environment config +(default)
 title=${1:-${title:-Markdown Viewer}};	
 d=${2:-${dimensions:-720x480}};
@@ -19,6 +50,6 @@ file=${3:-${file:--}};
 
 perl "$lib" --html4tags "${file}" \
 |	 ghtml ${debug:--}d --width ${d%*x} --height ${d#*x} --title "${title:-${file#*/}}" \
-	-o "${onload:-}" \
+	-o "$function_js_load_css" $MRKDNV_PROFILE $MRKDNV_STYLE \
 & disown $!;
 
