More updates to app. installer
the -e option was not being processed in the proper order of operations and was therefore almost entirely ignored.

Modified: apps/install

diff --git a/apps/install b/apps/install
--- a/apps/install
+++ b/apps/install
@@ -20,10 +20,12 @@
 
 group="$1"; test $# -gt 0 && shift 1;
 
-test $# -gt 0 && test "$1" = '-e' && { shift 1; exec=true; }
+test "$1" = '-e' && { exec=true; test $# -gt 0 && shift 1; }
 
-test $# -gt 0 && { title="$1"; shift 1; }
+title="$1";
 
+test $# -gt 0 && { shift 1; }
+ 
 this="$0" localPath="${this%/*}" installHook="$localPath/$group/@installhook";
 installDefault="/usr/bin" installDir="${INSTALLDIR:-$installDefault}";
 
@@ -50,7 +52,7 @@ echo "of all valid resources belonging to group"'\n';
 echo "if title is -- all following arguments are passed to ";
 echo "$here/$localPath/group/@installhook"'\n';
 
-test -w $installDir ||
+test -w "$installDir" ||
 echo You must have sufficient privileges to perform this operation.'\n';
 
 exit;
@@ -60,6 +62,25 @@ exit;
 byTitle="$localPath/$group/$title";
 byInstallHook="$localPath/$group/@installhook";
 byGroup="$localPath/$group/$group";
+
+test "$exec" = "true" && {
+
+	test -x "$byTitle" && test -n "$title"  && {
+		exec "$byTitle" "$@";
+	} || {
+		echo '\n'"Listing of executable targets for $group:"'\n'
+		(
+			for file in `cd "$localPath/$group"; printf "%s\n" *`; do
+				test -x "$localPath/$group/$file" && {
+					haveTargets=true;
+					echo "$file";
+				}
+			done
+			test "$haveTargets" = "true" || echo NO TARGETS AVAILABLE FOR GROUP;
+		);  echo ""; 
+	};  exit;
+
+}
 
 test -z "$title" || test "$title" = '--' && {
 	test -e "$byInstallHook" && { (
@@ -72,45 +93,25 @@ test -z "$title" || test "$title" = '--' && {
 	resource="$byTitle";
 }
 
-test "$exec" = "true" && {
-
-	test -x "$byTitle" && test -n "$title"  && {
-		exec "$byTitle" "$@";
-	} || {
-		echo '\n'"Listing of executable targets for $group:"'\n'
-		(	IFS='\n';
-			for file in `cd "$localPath/$group"; echo *`; do
-				test -x "$localPath/$group/$file" && {
-					haveTargets=true;
-					echo "$file";
-				}
-			done
-			test "$haveTargets" = "true" || echo NO TARGETS AVAILABLE FOR GROUP;
-		);  echo ""; 
-	};  exit;
-
-} || {
-
-	echo "";
-	test ! -e "$resource" && {
-		(   cd "$localPath/$group";
-			echo "Listing of resources in $group:"'\n';
-			list=`echo -n *`
-			test -z "$list" && echo NO RESOURCES AVAILABLE FOR GROUP'\n' || echo \
-			"$list"'\n'
-		);  exit 1;
-	}
-
-	test -w $installDir || {
-		echo '\n'"You don't have sufficient privileges to perform this operation."'\n';
-		exit 1;
-	} >&2;
-
-	status=`cp -vt "$installDir" "$resource" 2>&- || \
-	echo -n "$this: $group: operation failed: " >&2;`;
-
-	echo "$status";
-
-	echo "";
-
+echo "";
+test ! -e "$resource" && {
+	(   cd "$localPath/$group";
+		echo "Listing of resources in $group:"'\n';
+		list=`echo -n *`
+		test -z "$list" && echo NO RESOURCES AVAILABLE FOR GROUP'\n' || echo \
+		"$list"'\n'
+	);  exit 1;
 }
+
+test -w $installDir || {
+	echo "You don't have sufficient privileges to perform this operation."'\n';
+	exit 1;
+} >&2;
+
+status=`cp -vt "$installDir" "$resource" 2>&- || \
+echo -n "$this: $group: operation failed: " >&2;`;
+
+echo "$status";
+
+echo "";
+
